MsgType AckSequence::getMsgType() const { return MsgType::AckSequence; }
MsgType BothInputs::getMsgType() const { return MsgType::BothInputs; }
MsgType ChangeConfig::getMsgType() const { return MsgType::ChangeConfig; }
MsgType ClientMode::getMsgType() const { return MsgType::ClientMode; }
MsgType ConfirmConfig::getMsgType() const { return MsgType::ConfirmConfig; }
MsgType ControllerMappings::getMsgType() const { return MsgType::ControllerMappings; }
MsgType ErrorMessage::getMsgType() const { return MsgType::ErrorMessage; }
MsgType GoBackN::getMsgType() const { return MsgType::GoBackN; }
MsgType InitialConfig::getMsgType() const { return MsgType::InitialConfig; }
MsgType InitialGameState::getMsgType() const { return MsgType::InitialGameState; }
MsgType IpAddrPort::getMsgType() const { return MsgType::IpAddrPort; }
MsgType IpcConnected::getMsgType() const { return MsgType::IpcConnected; }
MsgType JoystickMappings::getMsgType() const { return MsgType::JoystickMappings; }
MsgType JoysticksChanged::getMsgType() const { return MsgType::JoysticksChanged; }
MsgType KeyboardEvent::getMsgType() const { return MsgType::KeyboardEvent; }
MsgType KeyboardMappings::getMsgType() const { return MsgType::KeyboardMappings; }
MsgType MenuIndex::getMsgType() const { return MsgType::MenuIndex; }
MsgType NetplayConfig::getMsgType() const { return MsgType::NetplayConfig; }
MsgType OptionsMessage::getMsgType() const { return MsgType::OptionsMessage; }
MsgType PaletteManager::getMsgType() const { return MsgType::PaletteManager; }
MsgType Ping::getMsgType() const { return MsgType::Ping; }
MsgType PingStats::getMsgType() const { return MsgType::PingStats; }
MsgType PlayerInputs::getMsgType() const { return MsgType::PlayerInputs; }
MsgType RngState::getMsgType() const { return MsgType::RngState; }
MsgType SocketShareData::getMsgType() const { return MsgType::SocketShareData; }
MsgType SpectateConfig::getMsgType() const { return MsgType::SpectateConfig; }
MsgType SplitMessage::getMsgType() const { return MsgType::SplitMessage; }
MsgType Statistics::getMsgType() const { return MsgType::Statistics; }
MsgType SyncHash::getMsgType() const { return MsgType::SyncHash; }
MsgType TestMessage::getMsgType() const { return MsgType::TestMessage; }
MsgType TransitionIndex::getMsgType() const { return MsgType::TransitionIndex; }
MsgType UdpControl::getMsgType() const { return MsgType::UdpControl; }
MsgType Version::getMsgType() const { return MsgType::Version; }
MsgType VersionConfig::getMsgType() const { return MsgType::VersionConfig; }
