#!/bin/sh

files="*.cpp *.h targets/*.cpp targets/*.h lib/*.cpp lib/*.h tests/*.cpp tests/*.h"

# echo Checking dependencies...

tail -n +1 -- `ls -1 $files | sort | paste -sd " "` | grep "^#include\|^==>" > tmp
diff > /dev/null 2>&1 tmp .include

if [ $? -ne 0 ]; then

    # echo Dependencies changed!

    mv -f tmp .include
    exit 1

fi

# echo Dependencies unchanged

rm -f tmp
touch .depend
exit 0
