#!/bin/sh

START='NetplayState::CharaSelect'

sed -n '/$START/,$p' $1 | grep -F RngState > tmpsync1
sed -n '/$START/,$p' $2 | grep -F RngState > tmpsync2

diff tmpsync1 tmpsync2

rm tmpsync1 tmpsync2
