#!/bin/sh

INTERVAL=5

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    killall gdbserver.exe
    killall MBAA.exe
    rm -f tmp*
    exit 0
}

while :
do
    check=`ps -W | grep MBAA.exe`

    if [ "$check" == "" ]; then
        sleep $INTERVAL
    else
        ./attach
    fi
done
