#!/bin/sh

INTERVAL=1

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    killall gdbserver.exe
    rm -f tmp_*
    exit 0
}

while :
do
    check=`ps -W | grep MBAA.exe`

    if [ "$check" == "" ]; then
        sleep $INTERVAL
    else
        scripts/attach
    fi
done
