#!/bin/sh

INTERVAL=1
COUNT=1
FOLDER="/d/desyncs"

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    killall MBAA.exe
    exit 0
}

while :
do
    if [ -d "$FOLDER/desync_`printf %03d $COUNT`" ]; then
        COUNT=$((COUNT+1))
    else
        break
    fi
done

while :
do

    scripts/debug $@

    cat cccaster/sync.log | tail -n5 | grep --quiet Desync

    if (( $? == 0 )); then

        echo "$FOLDER/desync_`printf %03d $COUNT`"

        cp -rv cccaster /d/desyncs/desync_`printf %03d $COUNT`

        COUNT=$((COUNT+1))

    fi

    sleep $INTERVAL

done
