#!/bin/sh

REGEX='^[^ ]+ \[([0-9]+)\] NetplayState::([A-Za-z]+) \[([0-9]+):([0-9]+)\] ([A-Za-z]+): (.+)$'

cat $1 \
  | sed --quiet '/CharaSelect/,$p' \
  | grep 'Inputs\|Rollback\|Reinputs\|:0] RngState' \
  | sed --regexp-extended "s/$REGEX/\1 \2 \3 \4 \5 \6/" \
  | sed --regexp-extended 's/target=\[([0-9]+):([0-9]+)\]; actual=\[[0-9]+:[0-9]+\]/\1 \2/'
